#!/bin/bash
# 🚀 BOLÃO COPA 2026 - QUICK DEPLOYMENT REFERENCE

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   Bolão Copa 2026 - Docker Fullstack Deployment Commands   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# LOCAL DEVELOPMENT
echo "📦 LOCAL DEVELOPMENT (Full Stack)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Start all services:"
echo "   docker-compose up -d"
echo ""
echo "2️⃣  View logs:"
echo "   docker-compose logs -f app"
echo ""
echo "3️⃣  Access:"
echo "   🌐 Frontend: http://localhost:8080"
echo "   📚 API Docs: http://localhost:8080/docs"
echo "   🗄️  PgAdmin: http://localhost:5050"
echo ""
echo "4️⃣  Stop services:"
echo "   docker-compose down"
echo ""

# RAILWAY PRODUCTION
echo "🚀 RAILWAY PRODUCTION DEPLOYMENT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Login to Railway:"
echo "   railway login"
echo ""
echo "2️⃣  Link to project:"
echo "   railway link"
echo ""
echo "3️⃣  Deploy:"
echo "   railway up"
echo ""
echo "4️⃣  View logs:"
echo "   railway logs"
echo ""
echo "5️⃣  Open in browser:"
echo "   railway open"
echo ""

# TESTING
echo "✅ TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Build Docker image:"
echo "   docker build -t bolao:latest ."
echo ""
echo "Run Docker container:"
echo "   docker run -p 8080:8080 bolao:latest"
echo ""
echo "Test frontend build:"
echo "   cd frontend && npm run build"
echo ""

# CREDENTIALS
echo "🔐 TEST CREDENTIALS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Email:    test@bolao.com"
echo "Password: Test123456!"
echo ""

# DEBUGGING
echo "🐛 DEBUGGING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Check container status:"
echo "   docker-compose ps"
echo ""
echo "Enter container shell:"
echo "   docker-compose exec app /bin/bash"
echo ""
echo "View backend logs:"
echo "   docker-compose exec app tail -f /var/log/supervisor/backend.log"
echo ""
echo "View nginx logs:"
echo "   docker-compose exec app tail -f /var/log/supervisor/nginx.log"
echo ""
echo "Check database connection:"
echo "   docker-compose exec app psql $DATABASE_PUBLIC_URL"
echo ""

# CLEANUP
echo "🧹 CLEANUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Remove containers:"
echo "   docker-compose down"
echo ""
echo "Remove volumes (WARNING: deletes database):"
echo "   docker-compose down -v"
echo ""
echo "Prune all Docker data:"
echo "   docker system prune -a"
echo ""

# DOCUMENTATION
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📄 Full Deployment Guide: DEPLOYMENT.md"
echo "📄 Docker Summary: DOCKER_DEPLOYMENT_SUMMARY.md"
echo "🔗 GitHub: https://github.com/danilopinheiro08-dev/bolao-copa-2026"
echo ""
echo "╚════════════════════════════════════════════════════════════╝"
